### ISSUE TITLE
Stop stealing my designs

### ISSUE THREAD

**Issue by Montanax** [eugenkiss/chanobol#167]
This really rustled my jimmies.

I was astonished to see that someone took some screenshots of my unreleased app Miko and then literally stealing it to implement in their own app, claiming that the design was from "Wadim". Well let me get this clear, that is my design and this pretty much puts me in a position where people are going to assume I took the designs from your app while you actually stole them from mine.

You are free to use my designs but I do not appreciate this whatsoever.

**Comment by eugenkiss** [comment]
Oh, I'm sorry, this is a misunderstanding. If you look at the [Wiki](https://github.com/eugenkiss/chanobol/wiki/Notes) (first point) and #142 you can see that I attributed the design to you. The reference to Wadim is just that he suggested to make the REPLIES and MORE buttons non-bold. 

I actually wanted to emphasize more at least here on Github more were I took my insipration from (namely Chanu, Clover and your designs which are very good). On Play Store I don't want to refer to existing or soon-to-be released apps because that might become a reason for suspension. But as I said I will emphasize more here on Github where the design inspiration for the PostsView came from. I hope this unrustles your jimmies a bit.

**Comment by Montanax** [comment]
Thanks for clearing that up a bit, the thing that bothered me the most was the possible miss-credited design.

**Comment by eugenkiss** [comment]
Good to hear, I've updated the main wiki page: https://github.com/eugenkiss/chanobol/wiki
