### ISSUE TITLE
Embedded Webm's like the Clover App

### ISSUE THREAD

**Issue by mitchross** [eugenkiss/chanobol#80]
WebM's should not open up video view, they should work like Clover app. I've got the clover source code im working on seeing how it works.

**Comment by mitchross** [comment]
looks like clover does something like

   private void startVideo() {
        if (videoVisible) return;
        videoVisible = true;

        imageView.setVideo(post.imageUrl);
    }

**Comment by eugenkiss** [comment]
I've just tried it and it's pretty slick. I have nothing against this feature.

**Comment by mitchross** [comment]
@eugenkiss where did you add this code? Im not too familiar with your code base yet. Id like too see how you did it!

**Comment by eugenkiss** [comment]
Just to resolve any possible confusion: With "I've just tried it" I meant I just tried the feature in the Clover app not that I already implemented it.

But if I wanted to implement it I'd change the body of the following callback: https://github.com/eugenkiss/chanobol/blob/b1c4b342162d223a119154e64506daea28348705/src/main/java/anabolicandroids/chanobol/ui/posts/PostView.java#L236

That is, instead of creating an intent and starting an activity request I'd "just" add a fragment (say `WebmFragment`) with the fragment manager to the top of the back stack.

**Comment by eugenkiss** [comment]
Note: Webm-inline-playing should be handeld by `ImageActivity`.

**Comment by eugenkiss** [comment]
Reviews wish for auto-looping of WebM
